In [36]:
class Dog:
    def __init__(self, name):
        self.__name = name
        print(name)
    def bark(self):
        pass
class Doberman(Dog):
    def bark(self):
        print('woof')
class Greyhound(Dog):
    def __init__(self, name, color):
        super().__init__(name)
        self.color = color
        print(color)
    def bark(self):
        print('woo')

In [37]:
doberman = Doberman(name = 'dow')
doberman.bark()
greyhound = Greyhound(name = 'don', color = 'white')
greyhound.bark()

dow
woof
don
white
woo


In [48]:
class Money:
    def __init__(self, rubles: int = 0, coins: int = 0):
        self.__general = rubles * 100 + coins
        self.__rubles = self.__general // 100
        self.__coins = self.__general % 100 

    def summoney(self, rubles: int, coins: int):
        self.__general += rubles * 100 + coins
        self.__rubles = self.__general // 100
        self.__coins = self.__general % 100
        
    def submoney(self, rubles: int, coins: int):
        self.__general -= rubles * 100 + coins
        self.__rubles = self.__general // 100
        self.__coins = self.__general % 100
        return self.__general
        
    def dividesum(self, rubles: int, coins: int):
        print((rubles * 100 + coins) / self.__general)
    
    def divmoney(self, divider: float):
        self.__general /= divider
        self.__rubles = self.__general // 100
        self.__coins = self.__general % 100

    def multiplication_money(self, multiplier: float):
        self.__general *= multiplier
        self.__rubles = self.__general // 100
        self.__coins = self.__general % 100

    def comparison(self, comp1: float, comp2):
        if comp1 > comp2:
            print(comp1,'>',comp2)
        if comp1 < comp2:
            print(comp1,'<',comp2)
        else:
            print(comp1,'=',comp2)
            
    def balance(self):
        print(int(self.__rubles), ',', int(self.__coins), sep='')
        
    
        

In [50]:
money = Money()
money.summoney(rubles = 2, coins = 40)  
money.summoney(rubles = 1, coins = 110)  
money.balance()
money.submoney(rubles = 1, coins = 150)
money.balance()
money.divmoney(divider = 2.5)
money.balance()
money.dividesum(rubles = 1, coins = 80)
money.balance()
money.multiplication_money(6.98)
money.balance()
money.comparison(6.4, 9.4)



4,50
2,0
0,80
2.25
0,80
5,58
6.4 < 9.4


In [33]:
import numpy as np
class Matrix:
    def __init__(self, rows = 0, cols = 0):
        self.__rows = rows
        self.__cols = cols 
        self.__matrix = []
        
    def create_matrix(self):
        for i in range(self.__rows):#order
            temp = []
            for j in range(self.__cols):
                temp.append(i * self.__rows + j + 1)
            self.__matrix.append(temp)
        print(np.array(self.__matrix))
     
    def multiplication_matrix(self, multiplier: float):
        multiplication_matrix = []
        for i in range(self.__rows):
            multiplication_result = []
            for j in range(self.__cols):
                result = (i * self.__cols + j + 1) * multiplier
                multiplication_result.append(result)
            multiplication_matrix.append(multiplication_result)
        print(np.array(multiplication_matrix))
     

In [34]:
matrix = Matrix(4, 4)
matrix.create_matrix() 
matrix1 = Matrix(4, 4)
matrix1.create_matrix() 
matrix = matrix.multiplication_matrix(6)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 6 12 18 24]
 [30 36 42 48]
 [54 60 66 72]
 [78 84 90 96]]
