In [29]:
#матрицы
import random
import numpy as np
class Matrix_1:
    def __init__(self, rows: int ):
        self.__rows = rows
        self.__matrix = []
        #for i in range(rows):#custom
            #self.__matrix.append(int(input()))   
        for i in range(rows):#custom
            self.__matrix.append(random.randint(0, 100))
            
    def sum_elements(self):
        for i in range(len(self.__matrix)):
            result = sum(self.__matrix)
        print(result)
        return result

    @property
    def matrix(self):
        return self.__matrix
        
    def sumobject(self, matrix):
        result = []
        for x, y in zip(self.__matrix, matrix.__matrix):
            result.append(x + y)
        print(result)
        
    def multobject(self, matrix):
        result = []
        for x, y in zip(self.__matrix, matrix.__matrix):
            result.append(x * y)
        print(result)
                          
    def show_matrix(self):
        print(self.__matrix)

class Matrix_2(Matrix_1):
    def __init__(self, rows = 0, cols = 0):
        super().__init__(rows)
        self.__matrix = []
        self.__rows = rows
        self.__cols = cols 
        
    def create_matrix(self):
        for i in range(self.__rows):#order
            temp = []
            for j in range(self.__cols):
                temp.append(i * self.__rows + j + 1)
            self.__matrix.append(temp)
        print(np.array(self.__matrix))

    def sum_elements(self):
        result = 0
        for i in range(self.__rows):
            for j in range(self.__cols):
                result += self.__matrix[i][j]
        print(result)
        
    @property
    def matrix(self):
        return self.__matrix
            
    @property
    def size(self):
        return self.__rows, self.__cols 
        
    def sumobject(self, matrix):
        result = []
        if self.size == matrix.size:
            for i in range(self.__rows):
                temp = []
                for j in range(self.__cols):
                    temp.append(self.__matrix[i][j] + matrix.__matrix[i][j])
                result.append(temp)
            print(np.array(result))
        else:
            print('Размерность матриц не совпадвет!')

    def multobject(self, matrix):
        result = []
        if self.size == matrix.size:
            for i in range(self.__rows):
                temp = []
                for j in range(self.__cols):
                    temp.append(self.__matrix[i][j] * matrix.__matrix[i][j])
                result.append(temp)
            print(np.array(result))
        else:
            print('Размерность матриц не совпадвет!')

    def saddle_point(self):
        find = False
        for i in range(self.__rows):
            min_el = min(self.__matrix[i])
            j = self.__matrix[i].index(min_el)
            column = [self.__matrix[m][j] for m in range(self.__rows)]
            max_el = max(column)
            if min_el == max_el:
                print(f'Седловая точка: {min_el} в позиции ({i}, {j})')
                find = True
        if not find:
            print('Седловой точки нет!')

class Matrix_3(Matrix_2):
    def __init__(self, rows = 0, cols = 0, height = 0):
        super().__init__(rows, cols)
        self.__rows = rows
        self.__cols = cols 
        self.__height = height
        self.__matrix = []  
        
    def create_matrix(self):
        for i in range(self.__rows):#random  
            t = []
            for j in range(self.__cols):
                temp = []
                for k in range(self.__height):
                    temp.append(random.randint(0, 100))
                t.append(temp)
            self.__matrix.append(t)
        print(np.array(self.__matrix))    
        
    def sum_elements(self):
        result = 0
        for i in range(self.__rows):
            for j in range(self.__cols):
                for k in range(self.__height):
                    result += self.__matrix[i][j][k]
        print(result)   

    @property
    def matrix(self):
        return self.__matrix
            
    @property
    def size(self):
        return self.__rows, self.__cols 
        
    def sumobject(self, matrix):
        if self.size == matrix.size:
            sum = []
            for i in range(self.__rows):
                result = []
                for j in range(self.__cols):
                    temp = []
                    for k in range(self.__height):
                        temp.append(self.__matrix[i][j][k] + matrix.__matrix[i][j][k])
                    result.append(temp)
                sum.append(result)
            print(np.array(sum))  
        else:
            print('Размерность матриц не совпадвет!')

    def multobject(self, matrix):
        if self.size == matrix.size:
            mul = []
            for i in range(self.__rows):
                result = []
                for j in range(self.__cols):
                    temp = []
                    for k in range(self.__height):
                        temp.append(self.__matrix[i][j][k] * matrix.__matrix[i][j][k])
                    result.append(temp)
                mul.append(result)
            print(np.array(mul))  
        else:
            print('Размерность матриц не совпадвет!')

    def saddle_point(self):
        find = False
        for k in range(len(self.__matrix)):
            lim = self.__matrix[k] 
            for i in range(len(lim)):
                min_el = min(lim[i])
                j = lim[i].index(min_el)
                column = [lim[m][j] for m in range(len(lim))]
                max_el = max(column)
                if min_el == max_el:
                    print(f'Седловая точка: {min_el} в позиции ({i}, {j})')
                    find = True
        if not find:
            print('Седловой точки нет!')


In [30]:
matrix1 = Matrix_1(4)
matrix2 = Matrix_1(4)
matrix1.show_matrix()
matrix2.show_matrix()
matrix3 = Matrix_2(3, 3)
matrix33 = Matrix_2(3, 3)
matrix3.create_matrix()
matrix33.create_matrix()
matrix4 = Matrix_3(3, 3, 3)
matrix5 = Matrix_3(3, 3, 3)
matrix4.create_matrix()
matrix5.create_matrix()
matrix1.sum_elements()
matrix3.sum_elements()
matrix4.sum_elements()
matrix2.sumobject(matrix1)
matrix2.multobject(matrix1)
matrix3.sumobject(matrix33)
matrix3.multobject(matrix33)
matrix4.sumobject(matrix5)
matrix4.multobject(matrix5)
matrix3.saddle_point()
matrix4.saddle_point()

[61, 34, 23, 38]
[0, 48, 80, 100]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[20 25 34]
  [59 85 93]
  [86 22 99]]

 [[97 11 68]
  [33 63 56]
  [30 64 97]]

 [[62 92 71]
  [77 65 34]
  [21 45 15]]]
[[[81 75 49]
  [ 4 74 21]
  [33 54 57]]

 [[77 89 66]
  [84  4 68]
  [16 53 50]]

 [[71 94 71]
  [96 80 34]
  [60 22 79]]]
156
45
1524
[61, 82, 103, 138]
[0, 1632, 1840, 3800]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[[101 100  83]
  [ 63 159 114]
  [119  76 156]]

 [[174 100 134]
  [117  67 124]
  [ 46 117 147]]

 [[133 186 142]
  [173 145  68]
  [ 81  67  94]]]
[[[1620 1875 1666]
  [ 236 6290 1953]
  [2838 1188 5643]]

 [[7469  979 4488]
  [2772  252 3808]
  [ 480 3392 4850]]

 [[4402 8648 5041]
  [7392 5200 1156]
  [1260  990 1185]]]
Седловая точка: 7 в позиции (2, 0)
Седловой точки нет!
