In [31]:
import numpy as np
arr_A1 = np.array([[1, 2, 4],
                   [7, 5, -2],
                   [-2, 1, 3]])

arr_A2 = np.array([[0, 3, 4],
                   [-7, 1, -2],
                   [2, -1, 3]])

arr_A3 = np.array([[5, 2, 9],
                   [7, 0, -2],
                   [-2, 1, 6]])

arr_A4 = np.array([[1, -2, 8],
                   [7, 5, -2],
                   [-2, 3, 0]])

arr_A5 = np.array([[9, 2, 4],
                   [7, 5, -5],
                   [6, -2, 3]])

arr_B1 = np.array([[-1, 0, 3],
                   [2, -6, 1],
                   [-7, 1, 5]])

arr_B2 = np.array([[1, 2, 4],
                   [7, 0, -2],
                   [-3, -2, 5]])

arr_B3 = np.array([[1, -2, 1],
                   [7, 5, -2],
                   [-2, 8, 3]])

arr_B4 = np.array([[0, 2, 4],
                   [1, -3, -2],
                   [-2, 1, 3]])

arr_B5 = np.array([[8, 2, 4],
                   [0, 1, -3],
                   [-2, 1, 6]])

arr_C1 = np.array([[-2, 3],
                   [4, 0],
                   [7, -1]])

arr_C2 = np.array([[-3, 2],
                   [0, 4],
                   [-1, 7]])

arr_C3 = np.array([[-2, 3],
                   [4, 5],
                   [0, -1]])

arr_C4 = np.array([[0, 3],
                   [5, -4],
                   [7, -1]])

arr_C5 = np.array([[-2, 0],
                   [4, 8],
                   [1, -1]])

def summatrix(a, b):
    return np.add(a, b)
    
def submatrix(a, b):
    return np.subtract(a, b)
    
def dotmatrix(a, b):
    if len(b) == len(a[0]):
        return a.dot(b)
        
def multmatrix(a, b, c):
    if len(b) == len(a[0]):
        result = a.dot(b)
        if len(c) == len(result[0]):
            return result.dot(c)

In [34]:
print(summatrix(arr_A1, arr_B1))
print(summatrix(arr_A3, arr_B3))
print(summatrix(arr_B1, arr_A1))
print(dotmatrix(arr_A1, arr_C1))
print(multmatrix(arr_A1, arr_B1, arr_C1))

[[ 0  2  7]
 [ 9 -1 -1]
 [-9  2  8]]
[[ 6  0 10]
 [14  5 -4]
 [-4  9  9]]
[[ 0  2  7]
 [ 9 -1 -1]
 [-9  2  8]]
[[34 -1]
 [-8 23]
 [29 -9]]
[[ 193 -100]
 [ -50   35]
 [  92  -61]]


In [ ]:
Определитель
1) 4 * 48 + 4 * 54 - 5 * 44 = 188
2) 5 * (- 13) + (- 43) - 3 * 145 = - 543
3) 4 * 16 + 27 - 5 * 11 = 36
7) 3 * 43 - 2 * 37 - 1 * (- 10) = 65
8) 50 * 5 + 32 + 126 = 408
9) 7 * (- 37) - 6 * 6 - 1 * (- 7) = - 288
13) 2 * 104 - 3 * 160 + 116 = - 156
14) 17 - 3 * (- 21) + 2 * 40 = 160
15) 7 * (- 37) - 6 * 6 + 7 = - 288